spring.application.name=apiCalendario
server.port=8081

# Conexion a Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/calendariodb
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate crea/actualiza las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL de la API de Festivos (la que ya tienes corriendo en el puerto 8080)
festivos.api.url=http://localhost:8080/api/festivos
